# Generated by Django 3.2 on 2023-03-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0002_alter_sock_info_about_alter_sock_info_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermatch",
            name="unmatched",
            field=models.BooleanField(default=False),
        ),
    ]
