# Generated by Django 3.2 on 2023-03-14 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0003_usermatch_unmatched"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socklike",
            name="dislike",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dislike",
                to="app_users.sock",
            ),
        ),
        migrations.AlterField(
            model_name="socklike",
            name="like",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="like",
                to="app_users.sock",
            ),
        ),
        migrations.AlterField(
            model_name="usermatch",
            name="other",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="matched",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="usermatch",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="him",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
