# Generated by Django 4.1.7 on 2023-04-02 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0005_auto_20230315_1730"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socklike",
            name="sock",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sock_likes",
                to="app_users.sock",
            ),
        ),
        migrations.AlterField(
            model_name="usermatch",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_match",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
