# Generated by Django 4.2 on 2023-04-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_users", "0006_alter_socklike_sock_alter_usermatch_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sock",
            name="info_brand",
            field=models.CharField(
                choices=[
                    ("1", "Gucci"),
                    ("2", "D&G"),
                    ("3", "Pierre Cardin"),
                    ("4", "Nike"),
                    ("5", "Adidas"),
                    ("6", "Puma"),
                    ("7", "Converse"),
                    ("8", "Odd sock"),
                    ("9", "Hot sock"),
                    ("10", "From ma' gran'ma"),
                    ("11", "Aldi"),
                    ("12", "One Euro Shop"),
                    ("13", "Stolen"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="sock",
            name="info_color",
            field=models.CharField(
                choices=[
                    ("1", "Black"),
                    ("2", "Grey"),
                    ("3", "Red"),
                    ("4", "Orange"),
                    ("5", "Yellow"),
                    ("6", "Multicolor"),
                    ("7", "Blue"),
                    ("8", "Purple"),
                    ("9", "Green"),
                    ("10", "White"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="sock",
            name="info_condition",
            field=models.CharField(
                choices=[
                    ("1", "Brand new"),
                    ("2", "Sunday best"),
                    ("3", "Fairly used"),
                    ("4", "Well loved"),
                    ("5", "Regular one"),
                    ("6", "Stained"),
                    ("7", "Overused"),
                    ("8", "Colorless but still going."),
                    ("9", "Lost and found"),
                    ("10", "Involuntary Toesock"),
                    ("11", "Rescued from trash"),
                    ("12", "One of a kind"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="sock",
            name="info_fabric",
            field=models.CharField(
                choices=[
                    ("1", "Wool"),
                    ("2", "Cotton"),
                    ("3", "Polyester"),
                    ("4", "Bamboo"),
                    ("5", "Nylon"),
                    ("6", "Silk"),
                    ("7", "Latex"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sock",
            name="info_fabric_thickness",
            field=models.CharField(
                choices=[
                    ("1", "Fishnet"),
                    ("2", "Nylon thin"),
                    ("3", "Summer type"),
                    ("4", "Regular polyester"),
                    ("5", "Winter type"),
                    ("6", "Cushioned cozy one"),
                    ("7", "Double battery powered self warming one"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sock",
            name="info_inoutdoor",
            field=models.CharField(
                choices=[
                    ("1", "Indoor sock"),
                    ("2", "Netflix'n'Chill sock"),
                    ("3", "Love-live sock"),
                    ("4", "Sleeping sock"),
                    ("5", "Las Vegas sock"),
                    ("6", "Japanese vendor machine sock"),
                    ("7", "Gym sock"),
                    ("8", "Outdoor sock"),
                    ("9", "2-week used Festival sock"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sock",
            name="info_type",
            field=models.CharField(
                choices=[
                    ("1", "Invisible"),
                    ("2", "Toe sock"),
                    ("3", "Toe less"),
                    ("4", "Ankle"),
                    ("5", "Mid-calf"),
                    ("6", "Crew"),
                    ("7", "Calf"),
                    ("8", "Knee-high"),
                    ("9", "Gran'ma knitted sock"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, unique=True, verbose_name="email address"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="info_gender",
            field=models.CharField(
                choices=[
                    ("1", "Female"),
                    ("2", "Male"),
                    ("3", "Non-binary"),
                    ("4", "One of a kind"),
                    ("5", "Snail"),
                    ("6", "Unicorn"),
                    ("7", "Shoelace"),
                    ("8", "Prefer not to say"),
                ],
                max_length=10,
            ),
        ),
    ]
