# Generated by Django 4.1.4 on 2023-01-11 00:05

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "info_about",
                    models.TextField(
                        blank=True, help_text="Insert your story in here."
                    ),
                ),
                ("info_birthday", models.DateField(default=django.utils.timezone.now)),
                (
                    "info_gender",
                    models.CharField(
                        choices=[
                            ("female", "Female"),
                            ("male", "Male"),
                            ("unicorn", "Unicorn"),
                            ("shoelace", "Shoelace"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "location_city",
                    models.CharField(help_text="Where do you live?", max_length=255),
                ),
                ("location_latitude", models.FloatField(blank=True, null=True)),
                ("location_longitude", models.FloatField(blank=True, null=True)),
                (
                    "social_instagram",
                    models.URLField(
                        blank=True,
                        help_text="Url to your Instagram profile.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "social_facebook",
                    models.URLField(
                        blank=True,
                        help_text="Url to your Facebook profile.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "social_twitter",
                    models.URLField(
                        blank=True,
                        help_text="Url to your Twitter profile.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "social_spotify",
                    models.URLField(
                        blank=True,
                        help_text="Url to your Spotify profile.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Sock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("info_joining_date", models.DateField(auto_now_add=True)),
                (
                    "info_about",
                    models.TextField(
                        blank=True, help_text="Insert sock's story in here."
                    ),
                ),
                (
                    "info_fabric",
                    models.CharField(
                        choices=[
                            ("wool", "Wool"),
                            ("cotton", "Cotton"),
                            ("polyester", "Polyester"),
                            ("bamboo", "Bamboo"),
                            ("silk", "Silk"),
                            ("nylon", "Nylon"),
                            ("unknown", "Unknown"),
                        ],
                        help_text="Select main fabric",
                        max_length=20,
                    ),
                ),
                (
                    "info_fabric_thickness",
                    models.CharField(
                        choices=[
                            ("0", "Fishnets"),
                            ("1", "Nylon thin"),
                            ("2", "Fashion victim"),
                            ("3", "Summer type"),
                            ("4", "Winter type"),
                            ("5", "Cushioned Cozy one"),
                            ("6", "Double battery powered self warming one"),
                        ],
                        help_text="Select main fabric",
                        max_length=20,
                    ),
                ),
                (
                    "info_brand",
                    models.CharField(
                        choices=[
                            ("adidas", "Adidas"),
                            ("puma", "Puma"),
                            ("nike", "Nike"),
                            ("d_g", "D&G"),
                            ("gucci", "Gucci"),
                            ("aldi", "Aldi"),
                            ("grandma", "From'ma'grandma"),
                            ("stolen", "Stolen"),
                            ("oddsocks", "Odd socks"),
                            ("hotsocks", "Hot socks"),
                        ],
                        help_text="Select the brand.",
                        max_length=30,
                    ),
                ),
                (
                    "info_type",
                    models.CharField(
                        choices=[
                            ("toe_socks", "Toe Socks"),
                            ("invisible", "Invisible"),
                            ("ankle", "Ankle"),
                            ("crew", "Crew"),
                            ("mid_calf", "Mid-Calf"),
                            ("calf", "Calf"),
                            ("knee_high", "Knee-High"),
                            ("toe_less", "Toe less"),
                            ("knitted", "Ga'ma knitted socks"),
                        ],
                        help_text="Select the type.",
                        max_length=20,
                    ),
                ),
                (
                    "info_size",
                    models.CharField(
                        choices=[
                            ("25-31", "25-31"),
                            ("32-36", "32-36"),
                            ("36-40", "36-40"),
                            ("40-45", "40-45"),
                            ("44-47", "44-47"),
                            ("47+", "47+"),
                        ],
                        help_text="Select the size.",
                        max_length=20,
                    ),
                ),
                ("info_age", models.IntegerField(help_text="How old is the sock?")),
                (
                    "info_separation_date",
                    models.DateField(
                        default=django.utils.timezone.now, help_text="Lonely since?"
                    ),
                ),
                (
                    "info_condition",
                    models.CharField(
                        choices=[
                            ("0", "Brand new"),
                            ("1", "Fairly used"),
                            ("2", "Sunday best"),
                            ("3", "Well loved"),
                            ("4", "One of a kind"),
                            ("5", "Sporty"),
                            ("6", "Stained"),
                            ("7", "Overused"),
                            ("8", "Colorless but still going."),
                            ("9", "Involuntary Toesocks"),
                            ("10", "Lost and found"),
                            ("11", "Rescued from trash"),
                        ],
                        help_text="Select the condition of the sock.",
                        max_length=50,
                    ),
                ),
                (
                    "info_holes",
                    models.IntegerField(help_text="How many holes has the sock?"),
                ),
                (
                    "info_kilometers",
                    models.IntegerField(
                        help_text="How many kilometers has the sock walked?"
                    ),
                ),
                (
                    "info_inoutdoor",
                    models.CharField(
                        choices=[
                            ("0", "Indoor"),
                            ("1", "Outdoor"),
                            ("2", "Love live"),
                            ("3", "Sport"),
                        ],
                        help_text="Select the main environment of the sock.",
                        max_length=20,
                    ),
                ),
                (
                    "info_washed",
                    models.IntegerField(help_text="How often washed per month?"),
                ),
                (
                    "info_color",
                    models.CharField(
                        help_text="Description of a special interest of the sock.",
                        max_length=250,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sock",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfilePicture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_picture",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "other",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matched",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="him",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SockProfilePicture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=255)),
                (
                    "sock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_picture",
                        to="app_users.sock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SockLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dislike",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dislike",
                        to="app_users.sock",
                    ),
                ),
                (
                    "like",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="like",
                        to="app_users.sock",
                    ),
                ),
                (
                    "sock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="me",
                        to="app_users.sock",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessageMail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("sent_date", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mail",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessageChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("sent_date", models.DateField(auto_now_add=True)),
                ("seen_date", models.DateField(blank=True, null=True)),
                (
                    "other",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_receiving",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sending",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
