# Generated by Django 4.1.4 on 2023-01-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sock",
            name="info_name",
            field=models.CharField(
                default="this is a title",
                help_text="What is the socks name?",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
