# Generated by Django 3.2 on 2023-01-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="info_about",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="location_city",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="social_facebook",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="social_instagram",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="social_spotify",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="social_twitter",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
