# Generated by Django 4.1.4 on 2023-01-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0002_sock_info_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sock",
            name="info_age",
            field=models.PositiveSmallIntegerField(help_text="How old is the sock?"),
        ),
        migrations.AlterField(
            model_name="sock",
            name="info_holes",
            field=models.PositiveSmallIntegerField(
                help_text="How many holes has the sock?"
            ),
        ),
        migrations.AlterField(
            model_name="sock",
            name="info_kilometers",
            field=models.PositiveSmallIntegerField(
                help_text="How many kilometers has the sock walked?"
            ),
        ),
        migrations.AlterField(
            model_name="sock",
            name="info_washed",
            field=models.PositiveSmallIntegerField(
                help_text="How often washed per month?"
            ),
        ),
    ]
