# Generated by Django 4.1.4 on 2023-01-11 19:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0003_alter_sock_info_age_alter_sock_info_holes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofilepicture",
            name="image",
            field=cloudinary.models.CloudinaryField(
                default="photo", max_length=255, verbose_name="image"
            ),
            preserve_default=False,
        ),
    ]
