# Generated by Django 4.1.4 on 2023-01-11 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0004_userprofilepicture_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofilepicture",
            name="url",
        ),
    ]
