# Generated by Django 4.1.4 on 2023-01-12 10:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0005_remove_userprofilepicture_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sockprofilepicture",
            name="url",
        ),
        migrations.AddField(
            model_name="sockprofilepicture",
            name="image",
            field=cloudinary.models.CloudinaryField(
                default="sock_photo", max_length=255, verbose_name="image"
            ),
            preserve_default=False,
        ),
    ]
