# Generated by Django 4.1.4 on 2023-01-12 11:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0006_remove_sockprofilepicture_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sockprofilepicture",
            name="image",
        ),
        migrations.RemoveField(
            model_name="userprofilepicture",
            name="image",
        ),
        migrations.AddField(
            model_name="sockprofilepicture",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(
                default="image", max_length=255, verbose_name="profile picture"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofilepicture",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(
                default="profile_picture",
                max_length=255,
                verbose_name="profile picture",
            ),
            preserve_default=False,
        ),
    ]
