# Generated by Django 4.1.4 on 2023-01-12 19:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0007_remove_sockprofilepicture_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofilepicture",
            name="profile_picture",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="profile picture"
            ),
        ),
    ]
